# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.google.com/search?q=test&sca_esv=565813469&sxsrf=AM9HkKl6KLSU4b7vDDb5Q4hT8RGO8Ov8tQ%3A1694833542889&source=hp&ei=hhsFZbztM9ao-QausJzYCw&iflsig=AO6bgOgAAAAAZQUpli-bmKka-vkKvJPQE29VREINi2D1&ved=0ahUKEwi8yJn6kq6BAxVWVN4KHS4YB7sQ4dUDCAs&uact=5&oq=test&gs_lp=Egdnd3Mtd2l6IgR0ZXN0MgcQABiKBRhDMgcQABiKBRhDMgcQABiKBRhDMgcQABiKBRhDMgcQABiKBRhDMgsQABiABBixAxiDATILEAAYgAQYsQMYgwEyBxAAGIoFGEMyBRAAGIAEMgUQABiABEjUBFAAWMMCcAB4AJABAJgBmwGgAZwEqgEDMC40uAEDyAEA-AEBwgIEECMYJ8ICERAuGIAEGLEDGIMBGMcBGNEDwgIIEAAYgAQYsQM&sclient=gws-wiz")
    self.driver.set_window_size(788, 824)
    self.driver.find_element(By.CSS_SELECTOR, ".LatpMc:nth-child(1) .FMKtTb").click()
    self.driver.find_element(By.LINK_TEXT, "동영상").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".g:nth-child(2) .LC20lb")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.close()
  
