# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSelenium():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_selenium(self):
    self.driver.get("https://skhynix.benepia.co.kr/hynix/dualLogin.do")
    self.driver.set_window_size(788, 824)
    self.driver.find_element(By.ID, "loginId").click()
    self.driver.find_element(By.ID, "loginId").send_keys("2074661")
    self.driver.find_element(By.ID, "password2").send_keys("bdpdnjs05*")
    self.driver.find_element(By.ID, "password2").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".gray > span").click()
    self.driver.find_element(By.LINK_TEXT, "리조트").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "리조트 예약신청").click()
    self.vars["win8453"] = self.wait_for_window(2000)
    assert self.driver.switch_to.alert.text == "해당 기능은 리프레쉬 라운지 시스템으로 이관되었습니다."
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win8453"])
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.LINK_TEXT, "호텔/레저 제휴").click()
    assert self.driver.switch_to.alert.text == "해당 기능은 리프레쉬 라운지 시스템으로 이관되었습니다."
    self.driver.switch_to.window(self.vars["win8453"])
    self.driver.find_element(By.ID, "userId").click()
    self.driver.find_element(By.ID, "userId").send_keys("2074661")
    self.driver.find_element(By.ID, "userPass").send_keys("bdpdnjs05*")
    self.driver.find_element(By.ID, "userPass").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "userPass").click()
    self.driver.find_element(By.ID, "userPass").send_keys("bdpdnjs05*")
    self.driver.find_element(By.ID, "userPass").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "userPass").click()
    self.driver.find_element(By.ID, "userPass").send_keys("sdpdnjs05*")
    self.driver.find_element(By.ID, "userPass").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "userPass").click()
    self.driver.find_element(By.ID, "userPass").send_keys("gkslrrkwk3!")
    self.driver.find_element(By.ID, "loginBtn").click()
    self.driver.find_element(By.ID, "userPass").click()
    self.driver.find_element(By.CSS_SELECTOR, ".link-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.ID, "userId").click()
    self.driver.find_element(By.ID, "userId").send_keys("2074661")
    self.driver.find_element(By.CSS_SELECTOR, ".radio:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-sm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pop-inner:nth-child(2) .btn-done").click()
    self.driver.find_element(By.ID, "authorize").click()
    self.driver.find_element(By.ID, "authorize").send_keys("368902")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("bdpdnjs05*")
    self.driver.find_element(By.ID, "password_repeat").send_keys("bdpdnjs05*")
    self.driver.find_element(By.ID, "saveBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pop-inner:nth-child(1) .btn-done").click()
    self.driver.find_element(By.ID, "userPass").click()
    self.driver.find_element(By.ID, "userPass").send_keys("bdpdnjs05*")
    self.driver.find_element(By.ID, "loginBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".category-list:nth-child(1) .program-list:nth-child(1) .program-link-txt").click()
    self.driver.find_element(By.LINK_TEXT, "예약 신청").click()
    self.driver.find_element(By.LINK_TEXT, "법인 리조트 현황").click()
  
